gui:
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5" # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
  nerdFontsVersion: "3"
git:
  overrideGpg: true
  pagers:
    - externalDiffCommand: difft --context=$(cat "$DIFFTCTXFILE" 2>/dev/null || echo 3)
customCommands:
  - key: "}"
    context: "global"
    description: "Increase diff context"
    command: |
      C=$(cat "$DIFFTCTXFILE" 2>/dev/null || echo 3)
      echo $((C+1)) > "$DIFFTCTXFILE"
      echo "difft context: $(cat "$DIFFTCTXFILE")"
    output: "log"
  - key: "{"
    context: "global"
    description: "Decrease diff context"
    command: |
      C=$(cat "$DIFFTCTXFILE" 2>/dev/null || echo 3)
      N=$((C-1))
      [ $N -lt 0 ] && N=0
      echo $N > "$DIFFTCTXFILE"
      echo "difft context: $(cat "$DIFFTCTXFILE")"
    output: "log"
keybinding:
  universal:
    increaseContextInDiffView: <disabled>
    decreaseContextInDiffView: <disabled>
